name:  env_fundamentos
channels: 
  - conda-forge
  - defaults
dependencies: 
  - python
  - numpy
  - pandas
  - beautifulsoup4
  - httpx
  - tinydb
  - python-dotenv
  - rich
  - selenium
  - webdriver-manager
  - waybackpy